version: '3.3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
      front_net:

  elasticsearch:
    image: elasticsearch:6.8.4
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

    networks:
      back_net:

  kibana:
    image: kibana:6.8.4
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      back_net:
      front_net:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back_net:
      front_net:

networks:
  front_net:
  back_net:
