---
- name: Install and register gitlab-runner
  become: true

  hosts: gitlab-ci

  vars:
    gitlab_ci_host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

  tasks:
    - name: Add docker-compose
      template:
        src: "./docker-compose.yml.j2"
        dest: "/srv/gitlab/docker-compose.yml"

    - name: Tear down existing services
      docker_compose:
        project_src: "/srv/gitlab"
        state: absent

    - name: Create and start services
      docker_compose:
        project_src: "/srv/gitlab"
      register: output

    - name: Run `docker-compose up` again
      docker_compose:
        project_src: "/srv/gitlab"
        build: no
      register: output