plugin: gcp_compute
projects:
  - gitlab-ci-254717

auth_kind: serviceaccount
service_account_file: ./credentials.json
groups:
  gitlab-ci: "' gitlab-ci' in name"
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
